export const IRISH_COUNTIES = [
  'Antrim',
  'Armagh',
  'Carlow',
  'Cavan',
  'Clare',
  'Cork',
  'Derry',
  'Donegal',
  'Down',
  'Dublin',
  'Fermanagh',
  'Galway',
  'Kerry',
  'Kildare',
  'Kilkenny',
  'Laois',
  'Leitrim',
  'Limerick',
  'Longford',
  'Louth',
  'Mayo',
  'Meath',
  'Monaghan',
  'Offaly',
  'Roscommon',
  'Sligo',
  'Tipperary',
  'Tyrone',
  'Waterford',
  'Westmeath',
  'Wexford',
  'Wicklow',
] as const;

export const COUNTY_CITIES: Record<string, string[]> = {
  Dublin: [
    'Dublin City Centre',
    'Dublin 1', 'Dublin 2', 'Dublin 3', 'Dublin 4', 'Dublin 5',
    'Dublin 6', 'Dublin 6W', 'Dublin 7', 'Dublin 8', 'Dublin 9',
    'Dublin 10', 'Dublin 11', 'Dublin 12', 'Dublin 13', 'Dublin 14',
    'Dublin 15', 'Dublin 16', 'Dublin 17', 'Dublin 18', 'Dublin 20',
    'Dublin 22', 'Dublin 24',
    'Artane', 'Ashtown', 'Baldoyle', 'Ballinteer', 'Ballsbridge',
    'Ballyboden', 'Ballyfermot', 'Ballymun', 'Balbriggan', 'Blackrock',
    'Blanchardstown', 'Cabinteely', 'Cabra', 'Castleknock', 'Chapelizod',
    'Churchtown', 'Clondalkin', 'Clontarf', 'Coolock', 'Crumlin',
    'Dalkey', 'Donabate', 'Donnybrook', 'Drimnagh', 'Drumcondra',
    'Dundrum', 'Dún Laoghaire', 'Fairview', 'Finglas', 'Firhouse',
    'Foxrock', 'Glasnevin', 'Glasthule', 'Greystones',
    'Harold\'s Cross', 'Howth', 'Inchicore', 'Kilbarrack', 'Killester',
    'Kilmainham', 'Kilnamanagh', 'Kilternan', 'Leopardstown', 'Lucan',
    'Lusk', 'Malahide', 'Marino', 'Monkstown', 'Mount Merrion',
    'Mulhuddart', 'Ongar', 'Palmerstown', 'Phibsborough', 'Portmarnock',
    'Raheny', 'Ranelagh', 'Rathcoole', 'Rathfarnham', 'Rathmines',
    'Ringsend', 'Rush', 'Saggart', 'Sandymount', 'Sandyford',
    'Santry', 'Skerries', 'Smithfield', 'Stepaside', 'Stillorgan',
    'Stoneybatter', 'Sutton', 'Swords', 'Tallaght', 'Templeogue',
    'Terenure', 'Tyrrelstown', 'Walkinstown', 'Whitehall',
  ],
  Cork: [
    'Cork', 'Cork City',
    'Ballincollig', 'Ballinlough', 'Ballintemple', 'Ballyphehane',
    'Bandon', 'Bantry', 'Blackpool', 'Blackrock', 'Blarney',
    'Carrigaline', 'Carrigtwohill', 'Castletownbere', 'Clonakilty',
    'Cobh', 'Cork North', 'Cork South', 'Douglas', 'Dunmanway',
    'Fermoy', 'Glanmire', 'Glanworth', 'Kanturk', 'Kinsale',
    'Macroom', 'Mallow', 'Midleton', 'Millstreet', 'Mitchelstown',
    'Passage West', 'Ringaskiddy', 'Rathcormac', 'Schull', 'Skibbereen',
    'Togher', 'Youghal',
  ],
  Galway: [
    'Galway', 'Galway City',
    'Athenry', 'Athlone', 'Ballinasloe', 'Barna', 'Clarinbridge',
    'Clifden', 'Connemara', 'Gort', 'Headford', 'Loughrea',
    'Moycullen', 'Oranmore', 'Oughterard', 'Portumna', 'Renmore',
    'Salthill', 'Spiddal', 'Tuam',
  ],
  Limerick: [
    'Limerick', 'Limerick City',
    'Abbeyfeale', 'Adare', 'Askeaton', 'Bruff', 'Castleconnell',
    'Hospital', 'Kilmallock', 'Mungret', 'Newcastle West',
    'Pallasgreen', 'Patrickswell', 'Rathkeale',
  ],
  Waterford: [
    'Waterford', 'Waterford City',
    'Abbeyside', 'Ardmore', 'Butlerstown', 'Carrickbeg', 'Dungarvan',
    'Dunmore East', 'Ferrybank', 'Kilmacthomas', 'Lismore',
    'Portlaw', 'Stradbally', 'Tramore',
  ],
  Kildare: [
    'Naas', 'Newbridge', 'Maynooth', 'Celbridge', 'Athy',
    'Ballycane', 'Ballymore Eustace', 'Castledermot', 'Clane',
    'Kilcock', 'Kilcullen', 'Kildare Town', 'Kill', 'Leixlip',
    'Monasterevin', 'Rathangan', 'Sallins', 'Straffan', 'The Curragh',
  ],
  Wicklow: [
    'Bray', 'Greystones', 'Wicklow Town', 'Arklow',
    'Ashford', 'Aughrim', 'Avoca', 'Baltinglass', 'Blessington',
    'Carnew', 'Delgany', 'Enniskerry', 'Kilcoole', 'Kilmacanogue',
    'Newcastle', 'Rathdrum', 'Rathnew', 'Roundwood', 'Tinahely',
    'Wicklow',
  ],
  Meath: [
    'Navan', 'Drogheda', 'Ashbourne', 'Trim',
    'Athboy', 'Bettystown', 'Clonee', 'Duleek', 'Dunboyne',
    'Dunshaughlin', 'Enfield', 'Kells', 'Kilcock', 'Laytown',
    'Oldcastle', 'Ratoath', 'Slane', 'Stamullen', 'Summerhill',
  ],
  Kerry: [
    'Tralee', 'Killarney', 'Listowel',
    'Abbeyfeale', 'Ballybunion', 'Caherciveen', 'Castleisland',
    'Dingle', 'Killorglin', 'Kenmare', 'Kilgarvan', 'Milltown',
    'Rathmore', 'Sneem', 'Tarbert', 'Tralee',
  ],
  Donegal: [
    'Letterkenny', 'Donegal Town', 'Buncrana',
    'Ardara', 'Ballybofey', 'Ballyshannon', 'Bridgend', 'Bundoran',
    'Burnfoot', 'Carndonagh', 'Convoy', 'Dungloe', 'Falcarragh',
    'Glenties', 'Killybegs', 'Lifford', 'Manorcunningham', 'Milford',
    'Moville', 'Raphoe', 'Stranorlar',
  ],
  Clare: [
    'Ennis', 'Shannon', 'Kilrush',
    'Ballyvaughan', 'Bunratty', 'Clarecastle', 'Ennistymon',
    'Killaloe', 'Kildysart', 'Lahinch', 'Lisdoonvarna', 'Miltown Malbay',
    'Newmarket-on-Fergus', 'Scariff', 'Sixmilebridge', 'Spanish Point',
    'Tulla',
  ],
  Sligo: [
    'Sligo', 'Sligo Town', 'Tubbercurry',
    'Ballymote', 'Collooney', 'Coolaney', 'Drumcliff', 'Enniscrone',
    'Grange', 'Riverstown', 'Rosses Point', 'Strandhill',
  ],
  Tipperary: [
    'Clonmel', 'Nenagh', 'Thurles', 'Tipperary Town',
    'Borrisokane', 'Cahir', 'Carrick-on-Suir', 'Cashel', 'Fethard',
    'Killenaule', 'Roscrea', 'Templemore', 'Templetuohy',
  ],
  Louth: [
    'Drogheda', 'Dundalk', 'Ardee',
    'Blackrock', 'Carlingford', 'Castlebellingham', 'Dunleer',
    'Louth Village', 'Termonfeckin',
  ],
  Wexford: [
    'Wexford Town', 'Gorey', 'New Ross', 'Enniscorthy',
    'Arklow', 'Bunclody', 'Ferns', 'Kilmore Quay', 'Rosslare',
    'Rosslare Harbour', 'Taghmon', 'Wellingtonbridge',
  ],
  Laois: [
    'Portlaoise', 'Portarlington', 'Abbeyleix',
    'Ballylynan', 'Borris-in-Ossory', 'Castletown', 'Durrow',
    'Mountmellick', 'Mountrath', 'Rathdowney', 'Stradbally',
  ],
  Offaly: [
    'Tullamore', 'Birr', 'Edenderry',
    'Banagher', 'Clara', 'Kilbeggan', 'Ferbane', 'Portarlington',
    'Rhode', 'Shinrone',
  ],
  Westmeath: [
    'Athlone', 'Mullingar',
    'Castlepollard', 'Glasson', 'Kilbeggan', 'Killucan', 'Kinnegad',
    'Moate', 'Rochfortbridge', 'Tyrrellspass',
  ],
  Longford: [
    'Longford Town', 'Granard', 'Edgeworthstown',
    'Ballymahon', 'Drumlish', 'Lanesborough', 'Newtownforbes',
  ],
  Cavan: [
    'Cavan Town', 'Bailieborough', 'Belturbet',
    'Ballyconnell', 'Cootehill', 'Kingscourt', 'Oldcastle', 'Virginia',
  ],
  Monaghan: [
    'Monaghan Town', 'Carrickmacross', 'Castleblayney',
    'Clones', 'Emyvale',
  ],
  Roscommon: [
    'Roscommon Town', 'Boyle', 'Castlerea',
    'Ballaghaderreen', 'Ballinlough', 'Elphin', 'Strokestown',
  ],
  Leitrim: [
    'Carrick-on-Shannon', 'Manorhamilton',
    'Ballinamore', 'Dromahair', 'Drumshanbo', 'Kinlough', 'Mohill',
  ],
  Mayo: [
    'Castlebar', 'Ballina', 'Westport', 'Claremorris',
    'Achill', 'Ballinrobe', 'Balla', 'Ballyhaunis', 'Belmullet',
    'Crossmolina', 'Foxford', 'Killala', 'Kiltimagh', 'Louisburgh',
    'Newport', 'Swinford', 'Tuam',
  ],
  Kilkenny: [
    'Kilkenny City', 'Callan', 'Castlecomer',
    'Graiguenamanagh', 'Piltown', 'Thomastown', 'Urlingford',
  ],
  Carlow: [
    'Carlow Town', 'Muinebheag', 'Tullow',
    'Bagenalstown', 'Borris', 'Hacketstown', 'Leighlinbridge',
  ],
  Antrim: [
    'Antrim Town', 'Ballymena', 'Belfast', 'Carrickfergus',
    'Larne', 'Lisburn', 'Newtownabbey', 'Randalstown',
  ],
  Armagh: [
    'Armagh City', 'Lurgan', 'Portadown', 'Craigavon',
    'Keady', 'Markethill',
  ],
  Derry: [
    'Derry City', 'Londonderry', 'Limavady',
    'Maghera', 'Magherafelt',
  ],
  Down: [
    'Downpatrick', 'Bangor', 'Newry', 'Newtownards',
    'Ballynahinch', 'Comber', 'Dromore', 'Hillsborough', 'Holywood',
    'Kilkeel', 'Newcastle',
  ],
  Fermanagh: [
    'Enniskillen', 'Lisnaskea', 'Irvinestown',
    'Ballinamallard',
  ],
  Tyrone: [
    'Omagh', 'Dungannon', 'Cookstown', 'Strabane',
    'Clogher', 'Fintona',
  ],
};

export function getCitiesByCounty(county: string) {
  return COUNTY_CITIES[county] ?? [];
}
